/**
 * Mongoose schema for a result, including an AutoIncrement plugin for a unique result number.
 * @module models/result
 */

const mongoose = require('mongoose');
const AutoIncrement = require('mongoose-sequence')(mongoose);

/**
 * Result schema
 * @typedef {object} ResultSchema
 * @property {number} amount - The amount of the result
 * @property {Schema.Types.ObjectId} account - The account associated with the result
 * @property {Schema.Types.ObjectId} platform - The platform associated with the result
 * @property {Timestamp} createdAt - The timestamp the result was created
 * @property {Timestamp} updatedAt - The timestamp the result was last updated
 * @property {number} resultNo - The unique result number generated by the AutoIncrement plugin
 */

const { Schema } = mongoose;

const resultSchema = new Schema(
    {
        amount: {
            type: Number,
            required: true,
            trim: true,
        },
        account: {
            type: Schema.Types.ObjectId,
            ref: 'Account',
            required: true
        },
        platform: {
            type: Schema.Types.ObjectId,
            ref: 'Platform',
            required: true
        }
    },
    {
        timestamps: true,
    }
);

resultSchema.plugin(AutoIncrement, {inc_field: 'resultNo'});

/**
 * Formats a result object to JSON, removing the __v property.
 * @function toJSON
 * @memberof module:models/result~ResultSchema
 * @returns {object} - The result object with the __v property removed
 */
resultSchema.methods.toJSON = function () {
    const result = this;
    const resultObject = result.toObject();

    delete resultObject.__v;

    return resultObject;
}

module.exports = mongoose.model('Result', resultSchema);
